apiVersion: v1
kind: Service
metadata:
  name: vite-project
  namespace: horizontal-scaling
spec:
  type: NodePort
  selector:
    app: test-vite
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30021
